/* Generated By:JavaCC: Do not edit this line. CalcConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalcConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 40;
  /** RegularExpression Id. */
  int QUESTION = 41;
  /** RegularExpression Id. */
  int CHAMADA = 42;
  /** RegularExpression Id. */
  int DIRECAO = 43;
  /** RegularExpression Id. */
  int ID = 44;
  /** RegularExpression Id. */
  int STRING_LITERAL = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\";\"",
    "\"return\"",
    "\"print\"",
    "\"println\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"se\"",
    "\"then\"",
    "\"entao\"",
    "\"else\"",
    "\"senao\"",
    "\"while\"",
    "\"enquanto\"",
    "\"do\"",
    "\"faca\"",
    "\"{\"",
    "\"}\"",
    "\"func\"",
    "\",\"",
    "<NUM>",
    "<QUESTION>",
    "<CHAMADA>",
    "<DIRECAO>",
    "<ID>",
    "<STRING_LITERAL>",
  };

}
